const Config = {
  "name": "Swim Pictures.",
  "actions": {
    "Card01": {
      "displayName": "Read for Fun",
      "displayNameInShop": "Read for Fun",
      "image": "images/card/Read_For_Fun_16_9.png",
      "description": "No book reports, exams, or deadlines. Just me and a good book.",
      "moneyCost": 0,
      "energyCost": 1,
      "producesGrowthMindset": 1,
      "producesMoney": 0,
      "producesAttention": 1,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card01"
    },
    "Card02": {
      "displayName": "Uncle Zhao's: Tips",
      "displayNameInShop": "Uncle Zhao's: Extra Shift",
      "image": "images/card/Money_Bill_16_9.png",
      "description": "Uncle Zhao always lets me work at his restaurant for a few extra bucks.",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 1,
      "producesAttention": 0,
      "producesEnergy": 1,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card02"
    },
    "Card03": {
      "displayName": "Meditation",
      "displayNameInShop": "Meditation",
      "image": "images/card/Meditation_16_9.png",
      "description": "Empty your mind of everything except Meditation. And Meditation.",
      "moneyCost": 2,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 8,
      "id": "Card03"
    },
    "Card04": {
      "displayName": "Visit Library",
      "displayNameInShop": "NY Public Library Card",
      "image": "images/card/Library_16_9.png",
      "description": "Books take you to new worlds!",
      "moneyCost": 1,
      "energyCost": 1,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 3,
      "discardsCards": 1,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card04"
    },
    "Card05": {
      "displayName": "Overnight Studying",
      "displayNameInShop": "Overnight Studying",
      "image": "images/card/Overnight_Study_16_9.png",
      "description": "Doing too much can make you tired.",
      "moneyCost": 2,
      "energyCost": 0,
      "producesGrowthMindset": 1,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 1,
      "producesStudyPoints": 0,
      "drawsCards": 1,
      "discardsCards": 0,
      "gainsCards": [
        "fatigue"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card05"
    },
    "Card06": {
      "displayName": "Healthy Cooking",
      "displayNameInShop": "Cookbook",
      "image": "images/card/Healthy_Food_16_9.png",
      "description": "Cooking for yourself can help you feel more energetic!",
      "moneyCost": 3,
      "energyCost": 1,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 3,
      "producesStudyPoints": 0,
      "drawsCards": 2,
      "discardsCards": 2,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card06"
    },
    "Card07": {
      "displayName": "Abundant Thinking",
      "displayNameInShop": "Abundant Thinking",
      "image": "images/card/Abundant_Thinking_16_9.png",
      "description": "I see no limits; only possibilities. The world is my oyster.",
      "moneyCost": 2,
      "energyCost": 1,
      "producesGrowthMindset": 1,
      "producesMoney": 1,
      "producesAttention": 1,
      "producesEnergy": 1,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [
        "Card07"
      ],
      "forgetsOnDiscard": true,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card07"
    },
    "Card08": {
      "displayName": "Jacket",
      "displayNameInShop": "Jacket",
      "image": "images/card/Jacket_16_9.png",
      "description": "Makes ya wanna go the extra mile. ",
      "moneyCost": 4,
      "energyCost": 0,
      "producesGrowthMindset": 1,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 2,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card08"
    },
    "Card09": {
      "displayName": "Busk on the Subway",
      "displayNameInShop": "Learn a Song",
      "image": "images/card/Music_16_9.png",
      "description": "Tips are hard to come by, but New Yorkers like their music.",
      "moneyCost": 2,
      "energyCost": 2,
      "producesGrowthMindset": 0,
      "producesMoney": 2,
      "producesAttention": 0,
      "producesEnergy": 1,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card09"
    },
    "Card10": {
      "displayName": "Sugar Rush",
      "displayNameInShop": "Energy Drink",
      "image": "images/card/Sugar_Rush_16_9.png",
      "description": "Pure energy... flowing through my veins...",
      "moneyCost": 5,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 1,
      "producesEnergy": 4,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 1,
      "gainsCards": [
        "fatigue"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card10"
    },
    "Card11": {
      "displayName": "S.M.A.R.T Goals",
      "displayNameInShop": "S.M.A.R.T Goals",
      "image": "images/card/Smart_Goal_16_9.png",
      "description": "I don't always make goals, but when I do, they are specific, measurable, attainable, relevant, and time-based.",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 1,
      "producesStudyPoints": 0,
      "drawsCards": 2,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card11"
    },
    "Card12": {
      "displayName": "Sell Sneakers",
      "displayNameInShop": "Invest in SneakerCorp",
      "image": "images/card/Sneaker_16_9.png",
      "description": "The trick to being successful with an E-Commerce business specializing in Streetwear is to make absolutely sure",
      "moneyCost": 6,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 3,
      "producesAttention": 1,
      "producesEnergy": 1,
      "producesStudyPoints": 0,
      "drawsCards": 1,
      "discardsCards": 1,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card12"
    },
    "fatigue": {
      "displayName": "Fatigue",
      "displayNameInShop": "Fatigue",
      "image": "images/card/Fatigue_16_9.png",
      "description": "Better rest up or I'll just get even more tired later.",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "fatigue"
    },
    "summerHomework": {
      "displayName": "Summer Homework",
      "displayNameInShop": "Summer Homework",
      "image": "images/card/Homework_16_9.png",
      "description": "So tedious...",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 1,
      "producesMoney": 0,
      "producesAttention": 1,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": true,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "summerHomework"
    },
    "Card15": {
      "displayName": "Bargain Hunting",
      "displayNameInShop": "Bargain Hunting",
      "image": "images/card/Shopping_16_9.png",
      "description": "A good eye helps me see deals others might miss.",
      "moneyCost": 3,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 1,
      "producesAttention": 1,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 3,
      "discardsCards": 3,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card15"
    },
    "Card16": {
      "displayName": "Haunting Memory",
      "displayNameInShop": "Haunting Memory",
      "image": "images/card/Haunted_Memory_16_9.png",
      "description": "Always in the back of your mind...",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 2,
      "discardsCards": 0,
      "gainsCards": [
        "fatigue"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 1,
      "id": "Card16"
    },
    "Card17": {
      "displayName": "Ascend to Olympus",
      "displayNameInShop": "Ascend to Olympus",
      "image": "images/card/Olympus_16_9.png",
      "description": "There are truly no limits to my potential as long as I work hard.",
      "moneyCost": 9,
      "energyCost": 0,
      "producesGrowthMindset": 1,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 2,
      "producesStudyPoints": 0,
      "drawsCards": 5,
      "discardsCards": 3,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card17"
    },
    "Card18": {
      "displayName": "Red Packet",
      "displayNameInShop": "Red Packet",
      "image": "images/card/Red_Packet_16_9.png",
      "description": "Too bad Chinese New Year only comes once a year.",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 5,
      "producesAttention": 0,
      "producesEnergy": 1,
      "producesStudyPoints": 0,
      "drawsCards": 1,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card18"
    },
    "Card19": {
      "displayName": "Music Club",
      "displayNameInShop": "Music Club",
      "image": "images/card/Music_Club_16_9.png",
      "description": "I love jamming in the school music club, but goodbye afternoons!",
      "moneyCost": 4,
      "energyCost": 1,
      "producesGrowthMindset": 3,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 1,
      "discardsCards": 2,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card19"
    },
    "Card20": {
      "displayName": "Counseling",
      "displayNameInShop": "Counseling",
      "image": "images/card/Therapist_16_9.png",
      "description": "I'm in a tough spot, but I have the courage to ask for help.",
      "moneyCost": 5,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [
        "Card03",
        "Card03"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card20"
    },
    "Card21": {
      "displayName": "Procastination",
      "displayNameInShop": "Procastination",
      "image": "images/card/Procrastination_16_9.png",
      "description": "\"I'll do this later\"",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 1,
      "discardsCards": 2,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card21"
    },
    "Card22": {
      "displayName": "Lazy",
      "displayNameInShop": "Lazy",
      "image": null,
      "description": "",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card22"
    },
    "Card23": {
      "displayName": "Daily Practice",
      "displayNameInShop": "Music Book",
      "image": "images/card/Music_Practice_16_9.png",
      "description": "If you really want to improve, make sure to practice every day!",
      "moneyCost": 4,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 1,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": true,
      "forgetsSelf": false,
      "forgetsCards": 1,
      "id": "Card23"
    },
    "Card24": {
      "displayName": "Make Memories",
      "displayNameInShop": "Make Memories",
      "image": "images/card/Make_Memory_16_9.png",
      "description": "Some memories last a lifetime.",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 1,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 3,
      "producesStudyPoints": 0,
      "drawsCards": 3,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card24"
    },
    "Card25": {
      "displayName": "Mentoring Workshop",
      "displayNameInShop": "Join Mentoring Program",
      "image": "images/card/Apex_16_9.png",
      "description": "Ah, a friend! A little late though. Ah well. ",
      "moneyCost": 1,
      "energyCost": 3,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [
        "Card11",
        "Card37"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card25"
    },
    "Card26": {
      "displayName": "Rich Cousins",
      "displayNameInShop": "Rich Cousins",
      "image": "images/card/Cousin_16_9.png",
      "description": "They like to rub their \"success\" in your face with lavish gifts.",
      "moneyCost": 4,
      "energyCost": 4,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 2,
      "gainsCards": [
        "Card18"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card26"
    },
    "Card27": {
      "displayName": "Learn to Swim",
      "displayNameInShop": "Swim Lessons",
      "image": "images/card/Swimming_16_9.png",
      "description": "I have to learn to swim for our Spring Trip!",
      "moneyCost": 0,
      "energyCost": 3,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 1,
      "discardsCards": 0,
      "gainsCards": [
        "Card39"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card27"
    },
    "Card28": {
      "displayName": "Study: Creative Writing",
      "displayNameInShop": "Study: Creative Writing",
      "image": "images/card/Study__Creative_Writing_16_9.png",
      "description": "Gives Study Points.",
      "moneyCost": 2,
      "energyCost": 2,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 1,
      "producesStudyPoints": 1,
      "drawsCards": 1,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card28"
    },
    "Card29": {
      "displayName": "Study: Watch Lecture",
      "displayNameInShop": "Study: Watch Lecture",
      "image": "images/card/Study__Online_Lecture_16_9.png",
      "description": "Gives Study Points.",
      "moneyCost": 6,
      "energyCost": 2,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 1,
      "producesStudyPoints": 2,
      "drawsCards": 1,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card29"
    },
    "Card30": {
      "displayName": "Study: Practice Math",
      "displayNameInShop": "Study: Practice Math",
      "image": "images/card/Study__Math_16_9.png",
      "description": "Gives Study Points.",
      "moneyCost": 3,
      "energyCost": 5,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 2,
      "drawsCards": 1,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card30"
    },
    "Card31": {
      "displayName": "Study: Science Lab",
      "displayNameInShop": "Study: Science Lab",
      "image": "images/card/Study__Science_16_9.png",
      "description": "Gives Study Points",
      "moneyCost": 4,
      "energyCost": 8,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 1,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [
        "fatigue"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card31"
    },
    "Card32": {
      "displayName": "Study: Read Textbook",
      "displayNameInShop": "Study: Read Textbook",
      "image": "images/card/Study__Textbook_16_9.png",
      "description": "Get study points.",
      "moneyCost": 10,
      "energyCost": 4,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 1,
      "drawsCards": 0,
      "discardsCards": 3,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card32"
    },
    "Card33": {
      "displayName": "Junk Food",
      "displayNameInShop": "Junk Food",
      "image": "images/card/Junk_Food_16_9.png",
      "description": "Delicious... but maybe I'll regret this later?",
      "moneyCost": 2,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 2,
      "producesStudyPoints": 0,
      "drawsCards": 1,
      "discardsCards": 0,
      "gainsCards": [
        "fatigue"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card33"
    },
    "Card34": {
      "displayName": "Lift Weights",
      "displayNameInShop": "Buy Dumbbells",
      "image": "images/card/Workout_16_9.png",
      "description": "Exercise is like studying, but for your body!",
      "moneyCost": 1,
      "energyCost": 1,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 1,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 2,
      "gainsCards": [
        "Card35"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card34"
    },
    "Card35": {
      "displayName": "Burst of Energy",
      "displayNameInShop": "Burst of Energy",
      "image": "images/card/Burst_Of_Energy_16_9.png",
      "description": "Your consistent exercise is really starting to pay off. You feel great!",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 2,
      "producesStudyPoints": 0,
      "drawsCards": 2,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": true,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card35"
    },
    "Card36": {
      "displayName": "Soccer With Friends",
      "displayNameInShop": "New Soccer Ball",
      "image": "images/card/After_School_Club_16_9.png",
      "description": "Video games are fun, but the weather outside is too good to miss!",
      "moneyCost": 1,
      "energyCost": 0,
      "producesGrowthMindset": 1,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 1,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [],
      "forgetsOnDiscard": false,
      "forgetsSelf": false,
      "forgetsCards": 0,
      "id": "Card36"
    },
    "Card37": {
      "displayName": "Year-End Project",
      "displayNameInShop": "Year-End Project",
      "image": "images/card/Meta_16_9.png",
      "description": "We might have bitten off more than we could chew...",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 0,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [
        "Card11",
        "fatigue"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card37"
    },
    "Card39": {
      "displayName": "Join Swim Team",
      "displayNameInShop": "Join Swim Team",
      "image": "images/card/Swim_Laps_16_9.png",
      "description": "My teacher is also coach of the school swim team. ",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 2,
      "producesStudyPoints": 0,
      "drawsCards": 1,
      "discardsCards": 0,
      "gainsCards": [
        "Card40"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card39"
    },
    "Card40": {
      "displayName": "Swim Practice",
      "displayNameInShop": "Swim Practice",
      "image": "images/card/Swim_Team_16_9.png",
      "description": "Practice is tiring, but I'm in the best shape of my life!",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 3,
      "producesStudyPoints": 0,
      "drawsCards": 1,
      "discardsCards": 0,
      "gainsCards": [
        "Card41"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card40"
    },
    "Card41": {
      "displayName": "Study: Swim Meet",
      "displayNameInShop": "Study: Swim Meet",
      "image": "images/card/Swim_Comp_16_9.png",
      "description": "I put in the work at Swim Practice. Now, all I can do is try my best!",
      "moneyCost": 0,
      "energyCost": 0,
      "producesGrowthMindset": 0,
      "producesMoney": 0,
      "producesAttention": 0,
      "producesEnergy": 0,
      "producesStudyPoints": 1,
      "drawsCards": 0,
      "discardsCards": 0,
      "gainsCards": [
        "Card40"
      ],
      "forgetsOnDiscard": false,
      "forgetsSelf": true,
      "forgetsCards": 0,
      "id": "Card41"
    }
  },
  "events": {
    "SummerStart": {
      "displayName": "Middle School Graduation",
      "image": "images/event/Middle_School_Graduation_3_2.png",
      "song": "songs/af.mp3",
      "description": "After a long year, you've finally graduated from middle school.",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 2,
      "indebtedTurns": 0,
      "energizedTurns": 2,
      "addsCardsToShop": [
        "Card36",
        "Card01",
        "Card02",
        "Card02"
      ],
      "addsCardsToDiscardPile": [
        "summerHomework",
        "summerHomework"
      ],
      "id": "SummerStart"
    },
    "SchoolStart": {
      "displayName": "High School Begins",
      "image": "images/event/School_3_2.png",
      "song": "songs/da.mp3",
      "description": "And just like that High School begins.",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card06",
        "Card33",
        "Card28",
        "Card25"
      ],
      "addsCardsToDiscardPile": [],
      "id": "SchoolStart"
    },
    "Event3": {
      "displayName": "It's getting Cold",
      "image": "images/event/School_Cold_3_2.png",
      "song": "songs/da.mp3",
      "description": "Winter finally begins to rise into the air of the cities. I hope you brought a jacket. This is the first difficulty rise of the game.",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 1,
      "inspiredTurns": 0,
      "indebtedTurns": 1,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card04",
        "Card08",
        "Card09",
        "Card03"
      ],
      "addsCardsToDiscardPile": [
        "fatigue"
      ],
      "id": "Event3"
    },
    "Event4": {
      "displayName": "Christmas Break!",
      "image": "images/event/Christmas_3_2.png",
      "song": "songs/af.mp3",
      "description": " Winter Break resides here. Things temporaily go back to what Summer Break was, excluding the winter cold and other normal things during this period",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 2,
      "indebtedTurns": 0,
      "energizedTurns": 2,
      "addsCardsToShop": [],
      "addsCardsToDiscardPile": [],
      "id": "Event4"
    },
    "Event5": {
      "displayName": "Spring Break",
      "image": "images/event/Spring_Break_3_2.png",
      "song": null,
      "description": "<FLAVOR>",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 2,
      "indebtedTurns": 0,
      "energizedTurns": 2,
      "addsCardsToShop": [],
      "addsCardsToDiscardPile": [],
      "id": "Event5"
    },
    "Event6": {
      "displayName": "Mom Falls Ill",
      "image": "images/event/Mom_Sick_3_2.png",
      "song": "songs/da.mp3",
      "description": "Mom's health took a non-fatal but somewhat serious decline. She has to go to the hosptial. She will recover, but doctors do not know how long it will take. Things are about to get much harder. ",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 2,
      "inspiredTurns": 0,
      "indebtedTurns": 2,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card20"
      ],
      "addsCardsToDiscardPile": [
        "Card21",
        "Card16",
        "fatigue",
        "Card22"
      ],
      "id": "Event6"
    },
    "Event7": {
      "displayName": "Second Semester",
      "image": "images/event/Prepare_For_School_3_2.png",
      "song": null,
      "description": "This is test text. Second semester has begun. Better study hard if you want to pass the SATs!",
      "clearsShop": true,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card15",
        "Card09",
        "Card09",
        "Card29",
        "Card30"
      ],
      "addsCardsToDiscardPile": [
        "fatigue"
      ],
      "id": "Event7"
    },
    "Event8": {
      "displayName": "Summer is Ending",
      "image": "images/event/Bedroom_3_2.png",
      "song": "songs/da.mp3",
      "description": "Let's make this summer one to remember!",
      "clearsShop": true,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card02",
        "Card02",
        "Card34",
        "Card07"
      ],
      "addsCardsToDiscardPile": [],
      "id": "Event8"
    },
    "Event9": {
      "displayName": "Dad's Business Struggling",
      "image": "images/event/Dad_Business_Struggle_3_2.png",
      "song": null,
      "description": "Dad hasn't been able to get the hours he usually gets at his job. I hope things turn around soon!",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 2,
      "inspiredTurns": 0,
      "indebtedTurns": 2,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card23"
      ],
      "addsCardsToDiscardPile": [
        "fatigue",
        "Card21",
        "Card16",
        "Card22"
      ],
      "id": "Event9"
    },
    "Event10": {
      "displayName": "First Semester Essays Due!",
      "image": "images/event/Exam_3_2.png",
      "song": null,
      "description": "Story point threshold check.",
      "clearsShop": false,
      "studyPointsThreshold": 1,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card03"
      ],
      "addsCardsToDiscardPile": [],
      "id": "Event10"
    },
    "Event11": {
      "displayName": "SAT WEEK",
      "image": "images/event/Exam_3_2.png",
      "song": null,
      "description": "<FLAVOR>",
      "clearsShop": false,
      "studyPointsThreshold": 3,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [],
      "addsCardsToDiscardPile": [
        "fatigue",
        "fatigue",
        "fatigue"
      ],
      "id": "Event11"
    },
    "Event12": {
      "displayName": "FINAL EXAMS",
      "image": "images/event/Exam_3_2.png",
      "song": null,
      "description": "<FLAVOR>",
      "clearsShop": false,
      "studyPointsThreshold": 10,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [],
      "addsCardsToDiscardPile": [],
      "id": "Event12"
    },
    "Event13": {
      "displayName": "It's getting Warmer",
      "image": "images/event/School_Warm_3_2.png",
      "song": null,
      "description": "Clubs are beginning to open up. Just in time, as there aren't many breaks here. ",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card26",
        "Card27",
        "Card19"
      ],
      "addsCardsToDiscardPile": [
        "Card18"
      ],
      "id": "Event13"
    },
    "Event14": {
      "displayName": "Premonition",
      "image": "images/event/Premonition_3_2.png",
      "song": null,
      "description": "You hear the teacher say there is a test in 3 weeks. Success, and you move on. Failure.... well, expect the school to not take this lightly. They'll likely take you to remedial classes, the very last thing your parents want to hear, and your parents will do anything to cover the shame.... even if it means throwing you out of the school. (Those study cards? You're going to need them.)",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card10"
      ],
      "addsCardsToDiscardPile": [
        "Card16",
        "Card22"
      ],
      "id": "Event14"
    },
    "Event15": {
      "displayName": "Third Semester",
      "image": "images/event/Prepare_For_School_3_2.png",
      "song": null,
      "description": "<FLAVOR>",
      "clearsShop": true,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card32",
        "Card31",
        "Card17"
      ],
      "addsCardsToDiscardPile": [],
      "id": "Event15"
    },
    "Event16": {
      "displayName": "Spring Trip",
      "image": "images/event/NYC_Travel_3_2.png",
      "song": null,
      "description": "The class has organized a trip to Florida. This year is finally coming to an end!",
      "clearsShop": false,
      "studyPointsThreshold": 5,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [
        "Card24"
      ],
      "addsCardsToDiscardPile": [],
      "id": "Event16"
    },
    "Event17": {
      "displayName": "Premonition 2",
      "image": "images/event/Premonition_3_2.png",
      "song": null,
      "description": "Mom and Dad seem tense. Something's not right.",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [],
      "addsCardsToDiscardPile": [],
      "id": "Event17"
    },
    "Event18": {
      "displayName": "Prom",
      "image": "images/event/Prom_3_2.png",
      "song": null,
      "description": "I like to move it; move it.",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [],
      "addsCardsToDiscardPile": [],
      "id": "Event18"
    },
    "Event19": {
      "displayName": "Event19",
      "image": null,
      "song": null,
      "description": "<FLAVOR>",
      "clearsShop": false,
      "studyPointsThreshold": 0,
      "engrossedTurns": 0,
      "inspiredTurns": 0,
      "indebtedTurns": 0,
      "energizedTurns": 0,
      "addsCardsToShop": [],
      "addsCardsToDiscardPile": [],
      "id": "Event19"
    }
  },
  "schedule": {
    "0": [
      "SummerStart"
    ],
    "2": [
      "Event8"
    ],
    "3": [],
    "4": [],
    "5": [
      "SchoolStart"
    ],
    "6": [],
    "8": [
      "Event3"
    ],
    "11": [
      "Event14"
    ],
    "14": [],
    "15": [
      "Event10"
    ],
    "16": [
      "Event4"
    ],
    "18": [
      "Event7"
    ],
    "19": [],
    "21": [
      "Event13"
    ],
    "22": [],
    "23": [
      "Event6"
    ],
    "24": [],
    "25": [],
    "28": [],
    "29": [
      "Event11"
    ],
    "30": [
      "Event5"
    ],
    "32": [
      "Event15"
    ],
    "34": [],
    "35": [
      "Event17"
    ],
    "36": [],
    "37": [
      "Event16"
    ],
    "38": [],
    "39": [],
    "40": [
      "Event9"
    ],
    "41": [],
    "43": [],
    "44": [
      "Event18"
    ],
    "45": [],
    "46": [],
    "47": [
      "Event12"
    ]
  },
  "timestamp": 1619842147586
};

export default Config;
